"""Deterministic transfer-function glyphs (the "what function does this node compute" half).

A ``pm.Deterministic("y", f(parents))`` gets a small CANONICAL, parameter-free glyph depicting the
transfer function ``f`` itself — an S-curve for ``invlogit``, an exponential for ``exp``, a line for an
affine linear predictor, a simplex for ``softmax``. Detection keys on the PRINCIPAL op of the
expression graph, and a glyph is emitted ONLY when its shape is a *provable consequence* of that
structure (ZERO false positives): we fall back to equation-only whenever the transform isn't reliably
depictable.

Three things make a positive provable rather than guessed (see docs/RESEARCH.md):
  * a curve ``T`` is drawn only when, after stripping value-preserving wrappers + scalar-constant affine
    framing, the core op IS an ``Elemwise{T}`` — elementwise application *means* ``y_i = T(z_i)`` pointwise;
  * a ``line`` is drawn only when the whole expression is provably degree ≤1 in the parent RVs
    (``_is_affine`` — a whitelist; ``parent*parent`` products are rejected);
  * everything else (``TrueDiv``, reductions, gather, non-constant ``Pow``, unknown/fused ops) falls
    through to skip.

Curve data is generated by evaluating the TRUE function on a fixed grid — never sampled through parents —
so it is deterministic and parent-independent (cf. ``glyph_data._canonical_bell``). Every branch is
guarded; any failure degrades to skip (never crash ``to_ir``).
"""

from __future__ import annotations

from typing import Any

import numpy as np

from ..ir import GlyphSpec
from .pytensor_latex import _is_wrapper, _scalar_op_name

_GRID = 64
_SRC = "deterministic_fn"
# Unary scalar ops we can depict as a canonical 1-D transfer curve (Pow is handled separately because it
# is binary and needs a constant exponent). Anything not here falls through to the affine / skip path.
_TRANSFERS = frozenset({"Sigmoid", "Erf", "Tanh", "Exp", "Log", "Log1p", "Softplus", "Sqrt", "Abs"})


# --------------------------------------------------------------------------- graph helpers
def _opof(v: Any) -> Any:
    o = getattr(v, "owner", None)
    return o.op if o is not None else None


def _depends_on_rv(t: Any) -> bool:
    from .constructs import (
        _depends_on_rv as dep,
    )  # lazy: constructs imports glyph_data which imports us

    return dep(t)


def _is_leaf(v: Any, named_ids: set, root_id: int) -> bool:
    """An atomic input: any *named* model variable (RV / deterministic / data), or a graph leaf. Mirrors
    ``pytensor_latex.render_value``'s leaf check so the detector stops at the same boundary the label
    does. The deterministic we're analyzing (``root_id``) is never itself a leaf."""
    if id(v) == root_id:
        return False
    if getattr(v, "owner", None) is None:
        return True
    return id(v) in named_ids


def _is_widening_cast(node: Any) -> bool:
    try:
        return (
            np.dtype(node.outputs[0].dtype).kind == "f"
        )  # int/float -> float keeps the value's shape
    except Exception:
        return False


def _unwrap(v: Any, named_ids: set, root_id: int) -> Any:
    """Strip value-preserving wrappers (ViewOp/DimShuffle/Identity, and widening Cast only)."""
    for _ in range(256):
        if _is_leaf(v, named_ids, root_id):
            return v
        op = _opof(v)
        if op is None:
            return v
        if _is_wrapper(op):
            v = v.owner.inputs[0]
            continue
        if _scalar_op_name(op) == "Cast" and _is_widening_cast(v.owner):
            v = v.owner.inputs[0]
            continue
        return v
    return v


def _scalar_const_sign(t: Any) -> int | None:
    """+1 / -1 if ``t`` is a parent-free SCALAR constant (or all-equal array) of a definite sign; None
    otherwise. Only such factors are safe to strip as shape-preserving framing."""
    if _depends_on_rv(t):
        return None
    try:
        a = np.asarray(t.eval(), dtype=float)
    except Exception:
        return None
    if not (a.ndim == 0 or (a.size > 0 and np.all(a == a.flat[0]))):
        return None  # a vector with varying entries would distort the shape
    val = float(a.flat[0]) if a.size else 0.0
    if val == 0.0:
        return None
    return 1 if val > 0 else -1


def _strip_framing(v: Any, named_ids: set, root_id: int) -> tuple[Any, int]:
    """Strip ONLY scalar-constant affine framing (provably shape-preserving), tracking net sign:
    ``Neg`` flips; ``Mul`` by scalar constants scales (sign tracked); ``Add``/``Sub`` by a scalar
    constant shifts (erased by [0,1] normalization). Never strips past a vector/data or parent operand."""
    sign = 1
    for _ in range(256):
        v = _unwrap(v, named_ids, root_id)
        if _is_leaf(v, named_ids, root_id):
            return v, sign
        sn = _scalar_op_name(_opof(v))
        ins = v.owner.inputs
        if sn == "Neg":
            sign = -sign
            v = ins[0]
            continue
        if sn in ("Add", "Sub", "Mul"):
            pd = [i for i in ins if _depends_on_rv(i)]
            if len(pd) != 1:
                return v, sign
            others = [i for i in ins if i is not pd[0]]
            signs = [_scalar_const_sign(o) for o in others]
            if any(s is None for s in signs):
                return v, sign  # non-scalar / indeterminate framing -> stop here
            if sn == "Mul":
                for s in signs:
                    sign *= s
            elif sn == "Sub" and pd[0] is ins[1]:
                sign = -sign  # const - a  ->  the varying part is -a
            v = pd[0]
            continue
        return v, sign
    return v, sign


def _is_affine(v: Any, named_ids: set, root_id: int, depth: int = 0) -> bool:
    """Provably degree ≤1 in the parent RVs (the line gate). A whitelist closed under exactly the
    degree-preserving ops; anything else (a transfer, TrueDiv, an unknown op) ⇒ False. ``Mul``/``Dot``
    admit at most one parent-dependent factor, so ``parent*parent`` (degree 2) is rejected."""
    if depth > 128:
        return False
    v = _unwrap(v, named_ids, root_id)
    if _is_leaf(v, named_ids, root_id):
        return True
    op = _opof(v)
    if op is None:
        return True
    n = type(op).__name__
    sn = _scalar_op_name(op)
    ins = v.owner.inputs
    if sn in ("Add", "Sub"):
        return all(_is_affine(i, named_ids, root_id, depth + 1) for i in ins)
    if sn == "Neg":
        return _is_affine(ins[0], named_ids, root_id, depth + 1)
    if sn == "Mul":
        pd = [i for i in ins if _depends_on_rv(i)]
        return len(pd) <= 1 and all(_is_affine(i, named_ids, root_id, depth + 1) for i in pd)
    if n in ("Dot", "Dot22", "Dot22Scalar", "Gemv", "CGemv", "BatchedDot"):
        return len([i for i in ins if _depends_on_rv(i)]) <= 1
    if n in ("Subtensor", "AdvancedSubtensor", "AdvancedSubtensor1"):
        return _is_affine(ins[0], named_ids, root_id, depth + 1)
    return False


# --------------------------------------------------------------------------- canonical curve builders
def _curve(xs: Any, ys: Any, sign: int) -> dict:
    """Normalize ys to [0, 1] (so any positive-affine framing is erased) and reflect if sign < 0."""
    xs = np.asarray(xs, dtype=float)
    ys = np.asarray(ys, dtype=float)
    lo, hi = float(np.min(ys)), float(np.max(ys))
    rng = (hi - lo) or 1.0
    norm = (ys - lo) / rng
    if sign < 0:
        norm = 1.0 - norm
    return {"xs": [float(x) for x in xs], "ys": [float(y) for y in norm]}


def _sigmoid(sign):
    xs = np.linspace(-6.0, 6.0, _GRID)
    return _curve(xs, 1.0 / (1.0 + np.exp(-xs)), sign)


def _probit(sign):
    from scipy.special import erf

    xs = np.linspace(-2.5, 2.5, _GRID)
    return _curve(xs, erf(xs), sign)  # erf is the S-shape (= probit up to rescaling)


def _tanh(sign):
    xs = np.linspace(-3.0, 3.0, _GRID)
    return _curve(xs, np.tanh(xs), sign)


def _exp(sign):
    xs = np.linspace(-2.0, 2.0, _GRID)
    return _curve(xs, np.exp(xs), sign)


def _log(sign):
    xs = np.linspace(0.05, 3.0, _GRID)
    return _curve(xs, np.log(xs), sign)


def _log1p(sign):
    xs = np.linspace(-0.9, 3.0, _GRID)
    return _curve(xs, np.log1p(xs), sign)


def _softplus(sign):
    xs = np.linspace(-3.0, 4.0, _GRID)
    return _curve(xs, np.log1p(np.exp(xs)), sign)


def _sqrt(sign):
    xs = np.linspace(0.0, 3.0, _GRID)
    return _curve(xs, np.sqrt(xs), sign)


def _abs_v(sign):
    xs = np.linspace(-2.0, 2.0, _GRID)
    return _curve(xs, np.abs(xs), sign)


def _line(sign):
    xs = np.linspace(-1.0, 1.0, _GRID)
    return _curve(xs, xs, sign)


def _power(k: float, sign):
    if k == int(k) and int(k) >= 1:  # integer power: defined on negatives (parabola / cubic / …)
        xs = np.linspace(-1.5, 1.5, _GRID)
    elif k < 0:
        xs = np.linspace(0.25, 2.0, _GRID)  # avoid the pole at 0
    else:
        xs = np.linspace(0.0, 2.0, _GRID)  # fractional power: positive domain (no complex values)
    return _curve(xs, np.power(xs, k), sign)


_TRANSFER_BUILDERS = {
    "Sigmoid": _sigmoid,
    "Erf": _probit,
    "Tanh": _tanh,
    "Exp": _exp,
    "Log": _log,
    "Log1p": _log1p,
    "Softplus": _softplus,
    "Sqrt": _sqrt,
    "Abs": _abs_v,
}


def _const_exponent(node: Any) -> float | None:
    """The exponent of a ``Pow`` Apply, if it is a parent-free scalar constant; else None."""
    try:
        exp = node.inputs[1]
    except Exception:
        return None
    if _depends_on_rv(exp):
        return None
    try:
        a = np.asarray(exp.eval(), dtype=float)
    except Exception:
        return None
    if a.ndim == 0 or (a.size > 0 and np.all(a == a.flat[0])):
        return float(a.flat[0]) if a.size else None
    return None


def _softmax_bars(var: Any) -> dict:
    """A schematic k-category probability vector (softmax outputs ONE point on the k-simplex, so k bars
    — distinct from a Dirichlet *prior over* the simplex, which gets marginal curves). k is the output
    dimension (structurally known); the bars are equal (the canonical no-information simplex point), so
    no specific probabilities are claimed. Honest: 'the output is a probability vector over k categories'."""
    k = 3
    try:
        sh = var.type.shape
        if sh and sh[-1] is not None and int(sh[-1]) >= 2:
            k = min(int(sh[-1]), 8)
    except Exception:
        pass
    return {"cats": list(range(k)), "heights": [1.0] * k}


# --------------------------------------------------------------------------- entry point
def transform_glyph(var: Any, named: dict | None = None):
    """Return ``(GlyphSpec, glyph_data, elision_reason)`` for a deterministic's transfer function, or
    ``(None, None, None)`` when it isn't provably depictable (→ equation-only). ``named`` is the
    ``id(var)->name`` map of all model variables (the leaf set)."""
    try:
        return _classify(var, named or {})
    except Exception:
        return None, None, None


def _classify(var: Any, named: dict):
    named_ids = set(named.keys())
    root_id = id(var)
    if _opof(var) is None:
        return None, None, None

    core, sign = _strip_framing(var, named_ids, root_id)
    core = _unwrap(core, named_ids, root_id)

    if _is_leaf(
        core, named_ids, root_id
    ):  # stripped to a single named var via scalar-affine framing
        return GlyphSpec(kind="curve", source=_SRC), _line(sign), None

    op = _opof(core)
    n = type(op).__name__
    sn = _scalar_op_name(op)

    if sn in _TRANSFERS:
        return GlyphSpec(kind="curve", source=_SRC), _TRANSFER_BUILDERS[sn](sign), None
    if sn == "Pow":
        k = _const_exponent(core.owner)
        if k is None or k == 1.0:
            return None, None, None  # non-constant exponent (or trivial) -> skip
        return GlyphSpec(kind="curve", source=_SRC), _power(k, sign), None
    if n == "Softmax":
        return GlyphSpec(kind="bars", source=_SRC), _softmax_bars(var), None

    # A pure gather/identity (a[idx] with no arithmetic) is technically affine but a reindex, not a
    # meaningful line — skip it.
    if n in ("Subtensor", "AdvancedSubtensor", "AdvancedSubtensor1"):
        return None, None, None

    if _is_affine(var, named_ids, root_id):
        return GlyphSpec(kind="curve", source=_SRC), _line(1), None
    return None, None, None
